### ISSUE TITLE
the script is great but not for everyone

### ISSUE THREAD

**Issue by ghost** [iamzubin/linux-setup#1]
this script is for only those distros that use apt package manager (debian based or ubuntu based). Not for arch based or fedora aur any other package manager! good for general ubuntu users!

**Comment by iamzubin** [comment]
well, yeah.
i made this script for myself. i also didnt have any user input or choices, as this script was not ment to be shared. but i did it anyway as github is free. 
well. if you want a arch or fedora version. i might not be the guy for that, i mostly use ubuntu latest LTS version.

**Comment by ghost** [comment]
Yeah! Its totally fine! Even i use 18.10😂😂😂😂
